### ISSUE TITLE
AVL_range_allocator fails to find free unaligned region

### ISSUE THREAD

**Issue by omriarad** [IBM/mcas#154]
During the process of creating a custom personality the following error was encountered:

```
[LOG]: Coded_exception code -1 cause << EXCEPTION - AVL_range_allocator: failed to find free unaligned region (size=1073741848 free=1368382544) >>
[WRN]: /specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/lib/libnupm/src/rc_alloc_avl.cpp:89 region allocation out-of-space (requested 1024 MiB, alignment=8)
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:77 write_hist() this(0x7f3cf8043bb0) pool 0x93a4002380 [range] alloc inject free
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [32..64): 24 0 20
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [512..1024): 1 0 0
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [8192..16384): 2 0 0
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [16384..32768): 1 0 0
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [32768..65536): 1 0 0
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [65536..131072): 1 0 0
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [134217728..268435456): 16 0 16
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [268435456..536870912): 4 0 4
/specific/disk1/home/sorting/mcas-pm-project-omri/mcas/src/components/store/hstore/src/heap_rc_ephemeral.h:85 write_hist() this(0x7f3cf8043bb0) [536870912..1073741824): 2 0 0
```
In this scenario I try to sort 8 key-value pair that allocate 128MiB value in MCAS in the following way:
- Iterate over the 8 key and for each of them :
- - create a new key-value pair that will hold the new value after sorting.
- - delete the old unsorted key-value pair via `cb_erase_key` & `cb_unlock`.
- Iterate over the sorted values and merge them iteratively:
- - Each two consecutive sorted chunks are merged, creating 2^(k−1) chunks
- - delete old unmerged chunks via `cb_erase_key` & `cb_unlock`.
For this purpose we created a pool the size of: 2*128MiB + 500b (where the 500b are another key-value pair that hold metadata and is created first)

On the third iteration of said merge (merging the only 2 remaining 512MiB arrays) we encounter the memory error (even though the pool appears to have enough free space and we have called `cb_erase_key`, when running with a pool the size of `3*128MiB + 500b` we no longer encounter this error (I'm assuming that for some reason even though we deleted the old values MCAS didn't leave a continuous memory region?).

**Comment by dickeycl** [comment]
That trace seems to show a bit more progress in the merge sort. 8 allocations between 128 GiB and 256GiB. But still, a 128MiB allocation failed. That is *almost* Working As Designed. I have added some text to the allocator dump to explain where the space is going. I say *almost* as designed because there is a tweak which I thought was in master, but is not. It is described at the  bottom.


Failed allocate 134217752 aligned 8:
area_top:
  area_ctl 0x93a4002640 (0x93a4002340..0x9434002340] :
    level 4, 18(1 free) x 0x8000000 bytes
The top level. 4. covers the entire tree. It consists of 18 "elements." They are 132MiB each. (Except the last one, which runs up against the end of available space, may be smaller.) An allocation can span up to 64 elements. Only 1 element in level 4 is free. The others are either entirely allocated to the "client" (the user of the allocator), or have been subdivided to provide smaller areas for allocation.
    0x93a4002340: element 0:1 subdivision
The first area (#0, for a length of 1), has been subdivided. This is always the case, as the metadata for a level is allocated at the beginning of the level, and is on the order of hundreds of bytes.
      area_ctl 0x93a4002580 (0x93a4002340..0x93ac002340] :
        level 3, 64(63 free) x 0x200000 bytes
The subdivision of the first level 4 blocks created 64 level 3 segments, each 2 MiB. One is used (subdivided into level 2 blocks), and 63 are free.
        0x93a4002340: element 0:1 subdivision
          area_ctl 0x93a40024c0 (0x93a4002340..0x93a4202340] :
            level 2, 64(59 free) x 0x8000 bytes
            0x93a4002340: element 0:1 subdivision
              area_ctl 0x93a4002400 (0x93a4002340..0x93a400a340] :
                level 1, 64(26 free) x 0x200 bytes
                0x93a4002340: element 0:2 reserved
Down at level 1, where segments are 512 bytes, 512*2 bytes are "reserved." This area holds the metadata for level 4, and for the first subdivisions of level 3 and level 2
                0x93a4002740: element 2:16 client.aligned
Element 2, for 16 elements, (512*16 bytes, 8 KiB) are used by the client. This is the first segment of the KV hash table. 
                0x93a4004740: element 18:16 client.aligned
At element 18, for 16 elements, another 512*16 bytes (8KiB) allocated 
                0x93a4006740: element 34:1 subdivision
                  area_ctl 0x93a4006740 (0x93a4006740..0x93a4006940] :
                    level 0, 64(3 free) x 0x8 bytes
                    0x93a4006740: element 0:24 reserved
Several small allocations here, 5 (33-40 byte) or 4 (25-32 bytes).
                    0x93a4006800: element 24:5 client.aligned
                    0x93a4006828: element 29:4 client.aligned
                    0x93a4006848: element 33:4 client.aligned
                    0x93a4006868: element 37:4 client.aligned
                    0x93a4006888: element 41:4 client.aligned
                    0x93a40068a8: element 45:4 client.aligned
                    0x93a40068c8: element 49:4 client.aligned
                    0x93a40068e8: element 53:4 client.aligned
                    0x93a4006908: element 57:4 client.aligned
                  area_ctl end
                end subdivision
                0x93a4006940: element 35:2 client.aligned
512 * 2 bytes allocated to the client. This may be the 500 byte application metadata, Why 2x512, if the application only asked for 500? Because a hash table "data" uses 24 bytes of metadata itself to keep track of size, etc. So the hash table would have the allocator for 524 bytes, which requires 2 512-byte elements. Note that 500 is very nearly a worst-case value; a request for, say 1024+24 (1048) bytes would have been satisfied with 3*512, or 1536 bytes.
                0x93a4006d40: element 37:1 subdivision
                  area_ctl 0x93a4006d40 (0x93a4006d40..0x93a4006f40] :
                    level 0, 64(35 free) x 0x8 bytes
                    0x93a4006d40: element 0:24 reserved
                    0x93a4006e00: element 24:5 client.aligned
                  area_ctl end
                end subdivision
              area_ctl end
            end subdivision
            0x93a400a340: element 1:1 subdivision
              area_ctl 0x93a400a400 (0x93a400a340..0x93a4012340] :
                level 1, 64(31 free) x 0x200 bytes
                0x93a400a340: element 0:1 subdivision
                  area_ctl 0x93a400a340 (0x93a400a340..0x93a400a540] :
                    level 0, 64(16 free) x 0x8 bytes
                    0x93a400a340: element 0:48 reserved
                  area_ctl end
                end subdivision
                0x93a400a540: element 1:32 client.aligned
                                0x93a400a540: element 1:32 client.aligned
              area_ctl end
            end subdivision
            0x93a4012340: element 2:1 client.aligned
            0x93a401a340: element 3:2 client.aligned
          area_ctl end
        end subdivision
      area_ctl end
    end subdivision
Back to level 0. There are 8 instances of 2*128MiB elements allocated. Remember that 500 (or 512) bytes was a worst case? So is 128MiB, as it also needs 24 bytes metadata, resulting in allocation request of 128MiB+24 bytes, which can only be satisfied by 2 128MiB regions.
    0x93ac002340: element 1:2 client.aligned
    0x93bc002340: element 3:2 client.aligned
    0x93cc002340: element 5:2 client.aligned
    0x93dc002340: element 7:2 client.aligned
    0x93ec002340: element 9:2 client.aligned
    0x93fc002340: element 11:2 client.aligned
    0x940c002340: element 13:2 client.aligned
    0x941c002340: element 15:2 client.aligned
  area_ctl end
area_top end
Failed allocate 134217752 aligned 8 end


Is it bad to have a some powers of 2 requests (as seen by the end user) be "worst case"? Yes. And does the allocator rely on powers of 2 for bit maps? Yes.

The worst case for allocation sizes is 8B*2^6n, for integral n. So 8B, 8B*2^6=512B, 8B*2^12=32KiB,  8B*2^18=2MiB, 8B*2^24=128MiB, 8B*2^30=8GiB.

 But there is no fundamental reason why the smallest allocation unit (8B) should be a power of 2. It could be 9 bytes, or 17 bytes. This would reduce the waste for pow2 allocations from 50% (worst case) to about 12% or 6% (worst case).

I thought this change was in master, but apparently it is not. I did make it and test it, and concluded that 9 was probably a better choice than 17.

**Comment by dickeycl** [comment]
In branch 154:
1) hstore-cc allocations are based on 9-byte elements, which should make hstore-cc waste less memory on power-of-2 allocations
2) In hstore (as well as hstore-cc), env var CCA_FINE_TRACE=1 will cause the allocator to print its allocation map when an allocation fails for lack of space. The name CCA_FINE_TRACE does not fit well in this context, as hstore uses the the "rcalb" allocator and not the "cca" allocator. But its probably better than choosing a different name, since the function is the similar.
